# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'insert_into_dues.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form6(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(410, 345)
        Form.setMinimumSize(QtCore.QSize(410, 345))
        Form.setMaximumSize(QtCore.QSize(410, 345))
        self.name = QtWidgets.QLabel(Form)
        self.name.setGeometry(QtCore.QRect(40, 20, 341, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.FIO_2 = QtWidgets.QLabel(Form)
        self.FIO_2.setGeometry(QtCore.QRect(30, 80, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.FIO_2.setFont(font)
        self.FIO_2.setObjectName("FIO_2")
        self.FIO_3 = QtWidgets.QLabel(Form)
        self.FIO_3.setGeometry(QtCore.QRect(30, 150, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.FIO_3.setFont(font)
        self.FIO_3.setObjectName("FIO_3")
        self.FIO_4 = QtWidgets.QLabel(Form)
        self.FIO_4.setGeometry(QtCore.QRect(30, 220, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.FIO_4.setFont(font)
        self.FIO_4.setObjectName("FIO_4")
        self.lineEdit_number = QtWidgets.QLineEdit(Form)
        self.lineEdit_number.setGeometry(QtCore.QRect(130, 80, 261, 31))
        self.lineEdit_number.setObjectName("lineEdit_number")
        self.lineEdit_number_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_number_2.setGeometry(QtCore.QRect(130, 150, 261, 31))
        self.lineEdit_number_2.setObjectName("lineEdit_number_2")
        self.lineEdit_number_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_number_3.setGeometry(QtCore.QRect(130, 220, 261, 31))
        self.lineEdit_number_3.setObjectName("lineEdit_number_3")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(130, 280, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Добавление записи"))
        self.name.setText(_translate("Form", "Добавление записи в таблицу Налоги"))
        self.FIO_2.setText(_translate("Form", "ФИО"))
        self.FIO_3.setText(_translate("Form", "Месяц"))
        self.FIO_4.setText(_translate("Form", "Зарплата"))
        self.pushButton.setText(_translate("Form", "Добавить"))
