# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update_table_dues.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form9(object):
    def setupUi(self, Form):
        Form.setObjectName("Изменение записи")
        Form.resize(409, 336)
        Form.setMinimumSize(QtCore.QSize(409, 336))
        Form.setMaximumSize(QtCore.QSize(409, 336))
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(120, 10, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.FIO_3 = QtWidgets.QLabel(Form)
        self.FIO_3.setGeometry(QtCore.QRect(20, 140, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.FIO_3.setFont(font)
        self.FIO_3.setObjectName("FIO_3")
        self.FIO_4 = QtWidgets.QLabel(Form)
        self.FIO_4.setGeometry(QtCore.QRect(20, 210, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.FIO_4.setFont(font)
        self.FIO_4.setObjectName("FIO_4")
        self.lineEdit_number_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_number_3.setGeometry(QtCore.QRect(120, 210, 261, 31))
        self.lineEdit_number_3.setObjectName("lineEdit_number_3")
        self.FIO_2 = QtWidgets.QLabel(Form)
        self.FIO_2.setGeometry(QtCore.QRect(20, 70, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.FIO_2.setFont(font)
        self.FIO_2.setObjectName("FIO_2")
        self.lineEdit_number = QtWidgets.QLineEdit(Form)
        self.lineEdit_number.setGeometry(QtCore.QRect(120, 70, 261, 31))
        self.lineEdit_number.setObjectName("lineEdit_number")
        self.lineEdit_number_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_number_2.setGeometry(QtCore.QRect(120, 140, 261, 31))
        self.lineEdit_number_2.setObjectName("lineEdit_number_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(120, 270, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Изменение записи"))
        self.label.setText(_translate("Form", "Изменение записи"))
        self.FIO_3.setText(_translate("Form", "Месяц"))
        self.FIO_4.setText(_translate("Form", "Зарплата"))
        self.FIO_2.setText(_translate("Form", "ФИО"))
        self.pushButton.setText(_translate("Form", "Изменить"))
